version: '3.8'
services:
  nginx:
    image: nginx:1.23
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
  emqx:
    container_name: hummingbot-broker
    image: emqx:5
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.local]
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc
    ports:
      - "1883:1883"  # mqtt:tcp
      - "8883:8883"  # mqtt:tcp:ssl
      - "8083:8083"  # mqtt:ws
      - "8084:8084"  # mqtt:ws:ssl
      - "8081:8081"  # http:management
      - "18083:18083"  # http:dashboard
      - "61613:61613"  # web-stomp gateway
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: http://localhost:3100/loki/api/v1/push
    # network_mode: host
  pgadmin:
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    image: dpage/pgadmin4:9.3.0
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@cyphercapital.com"
      PGADMIN_DEFAULT_PASSWORD: "Cypher@2025"
      PGADMIN_DISABLE_POSTFIX: ""
    restart: always
    ports:
      - 8000:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    # network_mode: host
  portainer:
    # ee for prod, ce for anything else
    image: portainer/portainer-ce:2.30.1
    command:  --admin-password-file /tmp/admin_password --http-enabled
    privileged: true
    restart: always
    ports: 
      - 9000:9000
    volumes: 
      - portainer-data:/data
      - ./creds/admin_password:/tmp/admin_password
      - /var/run/docker.sock:/var/run/docker.sock
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: http://localhost:3100/loki/api/v1/push
    # network_mode: host
  grafana:
    image: grafana/grafana:12.0.0
    privileged: false
    restart: always
    ports:
      - 3000:3000
    environment:
        GF_INSTALL_PLUGINS: "ayoungprogrammer-finance-datasource,grafana-simple-json-datasource"
    volumes:
      - grafana-data:/var/lib/grafana
  #  network_mode: host
  # loki:
  #   container_name: loki
  #   image: grafana/loki:3.4.1
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/mnt/config/loki-config.yaml
  #   volumes:
  #     - ./logs/loki:/var/log
  #     - ./:/mnt/config
  #   # networks:
  #   #   - loki

  # promtail:
  #   container_name: promtail
  #   image: grafana/promtail:3.4.1
  #   ports:
  #     - "9080:9080"
  #   volumes:
  #     - ./logs/promtail:/var/log
  #     - ./:/mnt/config
  #   command: -config.file=/mnt/config/promtail-config.yaml
    # networks:
    #   - loki
volumes:
  emqx-data: { }
  emqx-log: { }
  emqx-etc: { }
  grafana-data: { }
  pgadmin: { }
  portainer-data: { }
